### ISSUE TITLE
Adding margin between and Enhancing trending deals cards cards 

### ISSUE THREAD

**Issue by DevROHIT11** [mdazfar2/Ezyshop#1006] opened 2024-10-27 15:42 UTC
### Description

The trending deals cards are looking too much crowded i would like to add some margins to them by which they will look attractive  and also enhancing the UI of that cards 

please assign this Task to me , i really would like to work on your website.

### Screenshots

![Screenshot (66)](https://github.com/user-attachments/assets/abf92c1d-ddc5-438f-8500-4ad333dd00ba)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-28 17:45
Hey @DevROHIT11, set your screen size to 100% and then check again. It looks good and nice. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank you!_

**Closed** 2024-10-28 17:45 UTC
Labels: enhancement
