### ISSUE TITLE
[Feat]  Enhancement : Clicking on order cards doesn't open order summary

### ISSUE THREAD

**Issue by agnyaatha** [mdazfar2/Ezyshop#998] opened 2024-10-27 05:30 UTC
### Description

https://github.com/user-attachments/assets/76132823-1fdb-4848-b5a8-1c976a5d125a

Clicking only on right chevron button order summary page opens
Card should be made clickable 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-27 13:58
@agnyaatha, we will implement this after completing the payment integration because it is not possible to implement directly. We will just add this section as a frontend and nothing else. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank you!

**Closed by mdazfar2** 2024-10-27 13:58 UTC
Labels: enhancement
