### ISSUE TITLE
improve a nav bar

### ISSUE THREAD

**Issue by muskan-fatim** [mdazfar2/Ezyshop#1021] opened 2024-10-28 16:26 UTC
![image](https://github.com/user-attachments/assets/4b536652-1af5-4452-9412-fcd0203c8ca6)

**Comment by muskan-fatim** [comment] 2024-10-28 16:27
i just want to improve the apperance it seem messy nav bar i wil fix it

**Comment by mdazfar2** [comment] 2024-10-28 17:08
Hey @muskan-fatim, set your screen size to 100% and then check again. It looks good and nice. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank you!_

**Closed by mdazfar2** 2024-10-28 17:08 UTC

**Comment by muskan-fatim** [comment] 2024-10-28 18:15
thanks for your reply and sorry I find the valid issue next time
