### ISSUE TITLE
[BUG] Navbar items is misaligned and Home section not visible in dark mode

### ISSUE THREAD

**Issue by Ashish-Patnaik** [mdazfar2/Ezyshop#901] opened 2024-10-23 06:23 UTC
### Description

In the navbar the home section is very close to logo and in dark mode the home section is not visible in the navbar

### Screenshots

![22](https://github.com/user-attachments/assets/d03a7345-e60b-4ef9-a998-2f66f61047ee)
![222](https://github.com/user-attachments/assets/e5fabfff-a732-416a-ace8-17de76780258)

### Any additional information?

I want to work on this issue please assign me ,I will fix as soon as possible

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-23 07:49
Hey @Ashish-Patnaik, the navigation bar looks correct and very good on our side. Please check out the screenshot below for proof. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank You!_



![{E691A281-4DAD-46D8-B0CD-2BDE6FC96017}](https://github.com/user-attachments/assets/801202f9-2cd8-43dd-9a51-184c364b1b1d)

**Closed** 2024-10-23 07:49 UTC
Labels: bug
