### ISSUE TITLE
[Doc]: Navbar Menu is lack of proper spacing and alignment

### ISSUE THREAD

**Issue by Poushmita** [mdazfar2/Ezyshop#913] opened 2024-10-23 16:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Need proper spacing and adjustments in navbar

![image](https://github.com/user-attachments/assets/edfbc9d9-62a8-4f25-b330-95c7053c1476)

## Suggestions

- Can reduce the sizes of the Navbar menus to set all menus properly for all size of desktop-screen.
- Can set the proper spacing and remove the line-break property to adjust the name of Navbar-menus in single line.

### Rationale

Navbar is very eye catching for a website. So, it should look good to enhance a user experience.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-23 16:54
@Poushmita, the navigation bar looks correct and very good on our side. Please check out the screenshot below for proof. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank You!_



![{E691A281-4DAD-46D8-B0CD-2BDE6FC96017}](https://github.com/user-attachments/assets/801202f9-2cd8-43dd-9a51-184c364b1b1d)

**Closed** 2024-10-23 16:54 UTC
Labels: documentation
