### ISSUE TITLE
[BUG] Improving the login page in light and dark mode.

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [mdazfar2/Ezyshop#1000] opened 2024-10-27 05:55 UTC
### Description

Some icons are overlapping and there is misalignment in the button and the input box.Also non-hovering of the sign up link.

### Screenshots

https://github.com/user-attachments/assets/3c0be068-5398-4122-80c0-c941c7b0eab6

### Any additional information?

Please assign this issue to me.

### What browser are you seeing the problem on?

Safari

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-27 13:56
@Arghya-Chakraborty0812, set your screen size to 100% and then check again. It looks good and nice. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank you!

**Closed by mdazfar2** 2024-10-27 13:56 UTC
Labels: bug
