### ISSUE TITLE
login page not well proper

### ISSUE THREAD

**Issue by RahulPrasadYadav** [mdazfar2/Ezyshop#929] opened 2024-10-24 05:44 UTC
### Screenshots

![Screenshot (394)](https://github.com/user-attachments/assets/ecc67e83-6490-46fa-8246-5e30a8d1cc85)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by RahulPrasadYadav** [comment] 2024-10-24 05:45
@mdazfar2 assign the issue

**Comment by mdazfar2** [comment] 2024-10-24 14:40
Hey @RahulPrasadYadav, the login/signup page looks correct and very good on our side. Please check out the screenshot below for proof. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank You!


![image](https://github.com/user-attachments/assets/0a4a7ff5-6838-4d20-ab28-2f7947222c66)

**Closed by mdazfar2** 2024-10-24 14:40 UTC
Labels: bug
