### ISSUE TITLE
UI Enhancements: Align Images and Navbar Elements

### ISSUE THREAD

**Issue by Kavish-Paraswar** [mdazfar2/Ezyshop#977] opened 2024-10-26 05:17 UTC
![image](https://github.com/user-attachments/assets/26e654b6-dd30-4577-8e4a-eb6266b52ed0)
Align images in a single line for a more streamlined and visually appealing layout.

![image](https://github.com/user-attachments/assets/8355cf8d-5f56-413b-b93f-0a505c3beeff)
Ensure all navbar elements are properly aligned, improving usability and appearance.
Add icons or names for features like "Carts" and "My Wishlist" for a more intuitive navigation experience

With my strong background in HTML, CSS, and JavaScript, and considering the nature of the work required, I believe this task should be assigned as Level 2 or Level 3. Please assign this under GSoC '24 and Hacktoberfest.'

**Comment by mdazfar2** [comment] 2024-10-26 16:09
Hey @Kavish-Paraswar, the navigation bar looks correct and very good on our side. Please check out the screenshot below for proof. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank You!



![{E691A281-4DAD-46D8-B0CD-2BDE6FC96017}](https://github.com/user-attachments/assets/801202f9-2cd8-43dd-9a51-184c364b1b1d)

<br>



- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).

- Join our official [Discord](https://discord.gg/YnABU7tdU3) server where we can easily talk about how to enhance our project even better.


**Thank you!**

**Closed by mdazfar2** 2024-10-26 16:09 UTC

**Comment by Kavish-Paraswar** [comment] 2024-10-26 17:33
in the netifly link ,the navbar is done wrong , also do u dont want to align the images properly? @mdazfar2
