### ISSUE TITLE
[BUG] Spacing and Alignment Issue on Contact Page

### ISSUE THREAD

**Issue by Rahilsamani** [mdazfar2/Ezyshop#676] opened 2024-10-15 16:48 UTC
### Description

There are noticeable spacing and alignment issues on the contact page. Elements are not properly aligned, leading to a cluttered appearance. The current CSS properties for margin and padding do not resolve the layout problems. There may also be conflicting styles affecting the overall design.

### Screenshots

<img width="289" alt="image" src="https://github.com/user-attachments/assets/6dcd5a69-cfc0-44ff-b6fe-e0c6e1f0d650">

### Any additional information?

The problem is present on both mobile and desktop versions.
The issues affect the overall user experience and readability.
The problem persists across multiple browsers.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by SarangAhlawat** [comment] 2024-10-15 22:21
I want to work on this issue, please assign it to me under GSSoC'24 - Extd!
Also add gssoc-ext and level label.

**Comment by achalcipher** [comment] 2024-10-16 15:50
Hey people,

I've identified some spacing and alignment issues on the contact page. The elements aren't aligned properly, which leads to a cluttered appearance. The current CSS properties for margin and padding aren't resolving the layout problems, and there might be conflicting styles affecting the overall design.

Details:

The problem is present on both mobile and desktop versions.

It affects the overall user experience and readability.

The issue persists across multiple browsers.

**Closed** 2024-10-21 14:38 UTC
Labels: bug
