### ISSUE TITLE
improvement shopping cart 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [mdazfar2/Ezyshop#948] opened 2024-10-24 16:26 UTC
### Description

wee need to add  cart total .. cart coupon  and Address to more  atrective  website 

### Screenshots

![Screenshot (408)](https://github.com/user-attachments/assets/1c10917b-c54b-42f8-8d7f-b2385c7eed2b)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-24 16:43
Hey @RahulPrasadYadav, actually we are working on the seller dashboard, and there is pending work on the backend and databases. After completing that, we will let you know about working on this issue. For now, I am closing the issue. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank you!

**Closed by mdazfar2** 2024-10-24 16:43 UTC
Labels: enhancement
