### ISSUE TITLE
[BUG] Enhancement : Facilities section cards desaign

### ISSUE THREAD

**Issue by agnyaatha** [mdazfar2/Ezyshop#996] opened 2024-10-27 05:19 UTC
### Description

Issue :
1) Alignment of title
2) Font sizes are greater than the heading  

Proposed changes 
| BEFORE | AFTER |
| --- | --- |
| ![Screenshot 2024-10-27 104318](https://github.com/user-attachments/assets/059c9d53-d8c2-4df5-9fcc-e7c3cf8357ed) | ![Screenshot 2024-10-27 103710](https://github.com/user-attachments/assets/284959f5-b9ec-49c9-a2bc-b26649fb8819) |
| ![Screenshot 2024-10-27 104303](https://github.com/user-attachments/assets/31116ecc-0c7e-4d61-8fb5-f3810def6f85) | ![Screenshot 2024-10-27 103652](https://github.com/user-attachments/assets/adf4fd4c-eeff-4229-9c22-136b3dfdb079) |
| ![Screenshot 2024-10-27 104246](https://github.com/user-attachments/assets/a52bf346-1b4f-4e65-9be7-1f3ba8d90573) | ![Screenshot 2024-10-27 103634](https://github.com/user-attachments/assets/6b6544f8-57db-44fd-b370-59d499c41c21) |

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-27 13:49
@agnyaatha It looks good and very nice to our side. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank You!_

**Closed by mdazfar2** 2024-10-27 13:49 UTC
Labels: bug
