### ISSUE TITLE
[Enhance]: Allignment correction in main entry page ,

### ISSUE THREAD

**Issue by Jashwanth-rit** [mdazfar2/Ezyshop#756] opened 2024-10-18 09:38 UTC
### Description

The allignment of the "learn about us section" is basically wrong or not good looking , 
make it more attractive by incresing the size of the image present in left and create Box like model which , enhance User-Interface.

### Screenshots

![Screenshot 2024-10-18 150744](https://github.com/user-attachments/assets/9daca6dc-2ca4-41f8-96e6-d2be95dc4af0)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-18 09:47
Hey @Jashwanth-rit, actually, this is what we want. This is not a bug; it is intended to be exactly like this. Please raise another issue, which I'm happy to assign to you. However, make sure that the issue you raise is valid and genuinely needs to be addressed on our website; otherwise, invalid issues will be closed. Thank you!

**Closed by mdazfar2** 2024-10-18 09:47 UTC
Labels: enhancement

**Comment by Jashwanth-rit** [comment] 2024-10-18 09:55
checkout Issueno: #755 can I work on that , I am new to open source contribution.
