### ISSUE TITLE
[BUG] Not responsive on different screen sizes

### ISSUE THREAD

**Issue by agnyaatha** [mdazfar2/Ezyshop#995] opened 2024-10-27 04:50 UTC
### Description

Steps to reproduce :
1) Open app in developer window 
2) Change screen size 

The navbar overflow condition breaks the responsiveness.
Requires redesigning of navbar -> Could this be taken as a separate feature request? Let me know if you want me to propose one

### Screenshots

![image](https://github.com/user-attachments/assets/1ca1864e-9194-40a8-8d91-3307c6fce673)
![image](https://github.com/user-attachments/assets/e869c8f2-0b52-4975-8639-09342810e116)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-29 15:27
@agnyaatha, set your screen size to 100% and then check again. It looks good and nice. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank you!

**Closed by mdazfar2** 2024-10-29 15:27 UTC
Labels: bug
