### ISSUE TITLE
[BUG] Button does not work

### ISSUE THREAD

**Issue by inkerton** [mdazfar2/Ezyshop#1008] opened 2024-10-27 17:11 UTC
### Description

On clicking shop now It should check authorization and then It should or if loggedin it should redirect the user to that category.

### Screenshots

![image](https://github.com/user-attachments/assets/4aebbff6-63b9-479c-ba4d-6cab946038ca)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by inkerton** [comment] 2024-10-27 17:13
@mdazfar2 Can you assign me the issue.

**Comment by mdazfar2** [comment] 2024-10-28 02:06
@inkerton, this button is for the backend. When any seller adds their respective products, we will choose one of the best products according to the website and add products accordingly. These cards are only for display and will be implemented last, after the completion of the backend. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank You!

**Closed by mdazfar2** 2024-10-28 02:06 UTC
Labels: bug
