### ISSUE TITLE
[Feat] fix the login page

### ISSUE THREAD

**Issue by AE-Hertz** [mdazfar2/Ezyshop#1065] opened 2024-11-04 15:51 UTC
### Description

the current login page is not adequate as its having readbility issues and thiss will effect the potential customers.

Assign me this issue,

### Screenshots

![Screenshot 2024-11-04 212027](https://github.com/user-attachments/assets/c164c425-dc20-4cf1-9499-008393f282f8)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-11-04 16:11
hey @AE-Hertz, set your screen size to 100% and then check again. It looks good and nice. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank you!_

**Closed by mdazfar2** 2024-11-04 16:11 UTC
Labels: enhancement

**Comment by AE-Hertz** [comment] 2024-11-04 16:34
> hey @AE-Hertz, set your screen size to 100% and then check again. It looks good and nice. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank you!_

i think i didnot explained it properly, i was talking about the text which is not visible and can causing readability issues, if its happening with me only, than my bad.

**Comment by mdazfar2** [comment] 2024-11-04 17:05
@AE-Hertz, check out the screenshot below for proof that it looks good and is easy to read on our side. By the way, thank you for raising the issue.

<br>

![{A3BBBFDE-6611-4965-96DA-B2A96FB5C837}](https://github.com/user-attachments/assets/9112363c-ae57-4f6d-bbb1-2b6f36e7c339)

**Comment by AE-Hertz** [comment] 2024-11-04 17:09
> @AE-Hertz, check out the screenshot below for proof that it looks good and is easy to read on our side. By the way, thank you for raising the issue.
> 
> ![{A3BBBFDE-6611-4965-96DA-B2A96FB5C837}](https://private-user-images.githubusercontent.com/100375390/382848041-9112363c-ae57-4f6d-bbb1-2b6f36e7c339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDAzOTMsIm5iZiI6MTczMDc0MDA5MywicGF0aCI6Ii8xMDAzNzUzOTAvMzgyODQ4MDQxLTkxMTIzNjNjLWFlNTctNGY2ZC1iYmIxLTJiNmYzNmU3YzMzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxNzA4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzBmN2U0Y2UzYzhkYWZmZjQ5YTRiZjJmOGRjZjVkNGNjMDQ4MDI3ODg0NzE2N2JkZDk4YmQ2ZjJiMDFhNGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NNb7WF3oIj0zLsBw2Dau3s-uGK2vlRqnEUTHyNjAjOM)

ohh, nice . good to see its working properly. :} 

closing this issue, and if their is anything i can implement please let me know
