### ISSUE TITLE
[Feat] Add items to the cart

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [mdazfar2/Ezyshop#1004] opened 2024-10-27 13:23 UTC
### Description

There are no items in the shops and users are not able to add items to cart. I would like to implement add to cart functionality by placing some items in respective shops and also adding adding to cart feature.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-27 14:04
@Pallavi-Mukalla, the items are added by their shop owners only. I think you are not familiar with the project structure and how it works. Please read the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md) file for understanding and then raise an issue. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank you!

**Closed by mdazfar2** 2024-10-27 14:04 UTC
Labels: enhancement
