### ISSUE TITLE
[Doc]: Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [mdazfar2/Ezyshop#979] opened 2024-10-26 05:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute.

### Suggested Change

Wanted to do the following changes :-

1) Enhance the project structure
2) Add code of conduct section
3) Add star our repository section
4) Add need help with the basics section
5) Add first pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the thank you section

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-26 05:45
Hey @milansamuel609, actually, we already have good contributing guidelines. I mean, when a new contributor reads our guidelines, they can easily set up our project locally and run it successfully. I don't think there's a need to update the contributing guidelines.

As for the GitHub desktop, I agree that it's a good option, but users can also create and work with the command line, which looks more professional. Hope you understand.

I'm happy that you raised an issue in our repository regarding the contributing guidelines. Please raise another issue, which I'm happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed.



- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).

- Join our official [Discord](https://discord.gg/YnABU7tdU3) server where we can easily talk about how to enhance our project even better.


***Thank you!***

**Closed** 2024-10-29 15:28 UTC
Labels: documentation
