### ISSUE TITLE
🐞 [BUG] : Footer is missing social media icons

### ISSUE THREAD

**Issue by ashish-um** [mdazfar2/Ezyshop#903] opened 2024-10-23 08:25 UTC
### Description

The footer is missing icons for, github, linkedin, discord, and vercel.

### Screenshots

![Screenshot_20241023_135121-1](https://github.com/user-attachments/assets/cbde2490-f879-4f12-9790-b1f6929da035)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-23 10:26
Hey @veepanshu-kasana, the footer looks correct and very good on our side. Please check out the screenshot below for proof. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank You!_

**Closed** 2024-10-23 10:27 UTC
Labels: bug

**Comment by ashish-um** [comment] 2024-10-23 11:09
Try it on firefox, this issue seems to only be limited to firefox
