### ISSUE TITLE
[BUG] Horizontal scrolling in home page

### ISSUE THREAD

**Issue by Gauravtb2253** [mdazfar2/Ezyshop#1001] opened 2024-10-27 11:31 UTC
### Description

Hello
Currently there is horizontal scrolling in the home page
I would like to fix it

### Screenshots

![image](https://github.com/user-attachments/assets/d0baed33-c1f7-4a32-9d12-0c159e564692)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-27 13:52
Hey @veepanshu-kasana, the navigation bar looks correct and very good on our side. Please check out the screenshot below for proof. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. _Thank You!_



![{E691A281-4DAD-46D8-B0CD-2BDE6FC96017}](https://github.com/user-attachments/assets/801202f9-2cd8-43dd-9a51-184c364b1b1d)

**Closed by mdazfar2** 2024-10-27 13:52 UTC
Labels: bug
