### ISSUE TITLE
[BUG] Enhance Footer UI for Small Screen Sizes

### ISSUE THREAD

**Issue by dipexplorer** [mdazfar2/Ezyshop#1091] opened 2024-11-06 17:35 UTC
### Description

 The footer UI does not display optimally on smaller screens, resulting in cluttered elements and poor readability. Improving the footer layout for mobile devices will enhance usability and ensure that all content, such as social media icons, contact details, and branding, remains accessible and visually appealing.

### Screenshots

![06 11 2024_23 03 41_REC](https://github.com/user-attachments/assets/c1efca7e-f190-46ae-ab2e-3e362d0c005a)

### Any additional information?

Expected Outcome:

- A responsive footer layout that adjusts seamlessly for small screen sizes, with well-spaced and organized elements.
- Readable font sizes and properly aligned icons, contact details, and branding on mobile devices.
- Tested on various small screen sizes to ensure consistent and user-friendly presentation.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-11-07 04:36
Hey @dipexplorer, actually, this is what we want. This is not a bug; it is intended to be exactly like this. Please raise another issue, which I'm happy to assign to you. However, make sure that the issue you raise is valid and genuinely needs to be addressed on our website; otherwise, invalid issues will be closed. Thank you!

**Comment by dipexplorer** [comment] 2024-11-07 10:01
@mdazfar2 ,
Would you like to change the footer UI or not?

**Comment by mdazfar2** [comment] 2024-11-07 14:38
> @mdazfar2 , Would you like to change the footer UI or not?

Sorry @dipexplorer, I don't want to change the footer UI. Thank you for raising the issue :)

**Closed by mdazfar2** 2024-11-07 14:38 UTC
Labels: bug
