### ISSUE TITLE
[BUG] Proper allignment of login page 

### ISSUE THREAD

**Issue by HimangshuSharma01** [mdazfar2/Ezyshop#983] opened 2024-10-26 12:10 UTC
### Description

https://github.com/user-attachments/assets/bff38091-3b4b-4b55-8cbc-c24af947e24d

i can fix the Ui

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-26 16:08
Hey @HimangshuSharma01, the login/signup looks correct and very good on our side. Please check out the screenshot below for proof. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank You!



![{C0408F0A-BDCF-4E89-9C66-6C13809E7B24}](https://github.com/user-attachments/assets/d938d32f-6e75-4a83-a212-93a9b4500922)

<br/>


![image](https://github.com/user-attachments/assets/9ae9f7d0-e924-49ed-977c-ad4faad6cfb9)

**Closed by mdazfar2** 2024-10-26 16:08 UTC
Labels: bug
