### ISSUE TITLE
[Doc]: Organization of the Repository

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [mdazfar2/Ezyshop#388] opened 2024-10-09 20:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The repository is gradually increasing in size with more files being added. This necessitates **better organization** of the files to improve the project's **readability** and **accessibility**.

### Suggested Change

I would like to help organize the repository to enhance its readability and scalability, making it more **user-friendly** for new contributors who are trying to get involved in open source but may not yet be familiar enough to understand the project's structure on their own.

1. I would like to **structure the files** especially the web pages into a folder.
2. **Rename the files** according to the web pages(if required).

### Rationale

A **well-organized project** distinguishes itself from others. In a previous issue I worked on as a contributor, I encountered challenges in **locating the corresponding files** (web pages), which ultimately **delayed my progress**. Improving the organization of the repository will not only **streamline workflows** but also enhance the **overall contributor experience**, allowing everyone to work more **efficiently** and **effectively**.

### Urgency

High

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-09 21:36
Hey @rajdeepchakraborty-rc, thank you for raising that issue. We are currently converting the code to Next.js. If you're interested in contributing to our Next.js code, please let me know. We've completed our landing page in Next.js, but it doesn't match the current one in terms of text style, font, and several other things.

- The whole Next.js code is in the `Benjamin` directory within the Ezyshop root folder. Below, I provide the steps to run the Next.js project.


```bash
 cd Benjamin
```

```bash
 npm i
```


```bash
 npm run dev
```

- Then run in your browser `localhost:3000`


- Do changes what you want but make sure it is full duplicate of HTML, CSS.


***Thank you!***

**Closed by mdazfar2** 2024-10-09 21:36 UTC
Labels: documentation

**Comment by rajdeepchakraborty-rc** [comment] 2024-10-10 07:00
> Hey @rajdeepchakraborty-rc, thank you for raising that issue. We are currently converting the code to Next.js. If you're interested in contributing to our Next.js code, please let me know. We've completed our landing page in Next.js, but it doesn't match the current one in terms of text style, font, and several other things.
> 
> * The whole Next.js code is in the `Benjamin` directory within the Ezyshop root folder. Below, I provide the steps to run the Next.js project.
> 
> ```shell
>  cd Benjamin
> ```
> 
> ```shell
>  npm i
> ```
> 
> ```shell
>  npm run dev
> ```
> 
> * Then run in your browser `localhost:3000`
> * Do changes what you want but make sure it is full duplicate of HTML, CSS website which is now deployed.
> 
> _**Thank you!**_

@mdazfar2 I’m not very familiar with Next.js, but I’m willing to give it a try. If I feel confident about it, I’ll open an issue and keep you informed.
