### ISSUE TITLE
[BUG] Overlapping of cards in some parts 

### ISSUE THREAD

**Issue by agnyaatha** [mdazfar2/Ezyshop#997] opened 2024-10-27 05:25 UTC
### Description

Cards overlap on one another when screen size changes 

### Screenshots

![image](https://github.com/user-attachments/assets/fb6a1299-45c6-4f67-b83a-0b867234fef5)
![image](https://github.com/user-attachments/assets/ca74a636-5060-4204-b46d-c60acfb778de)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by arpithasm88** [comment] 2024-10-29 05:22
I am willing to work on this issue, please assign this to me

**Comment by mdazfar2** [comment] 2024-10-29 15:26
hey @agnyaatha @arpithasm88, set your screen size to 100% and then check again. It looks good and nice. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank you!

**Closed by mdazfar2** 2024-10-29 15:26 UTC
Labels: bug
