### ISSUE TITLE
Enchancing footer section of website 

### ISSUE THREAD

**Issue by Kavita1928** [mdazfar2/Ezyshop#115] opened 2024-10-03 17:43 UTC
### Description

make the footer section to look by properly arranging bars properly in home page

### Screenshots

![Screenshot 2024-10-03 231314](https://github.com/user-attachments/assets/d2cee136-e671-4927-9460-f3a481748723)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Abhi0049k** [comment] 2024-10-03 17:46
Hi @Kavita1928, can you assign this issue to me?

**Comment by Kavita1928** [comment] 2024-10-03 17:49
@Abhi0049k issue assigned to you

**Comment by Sujal942** [comment] 2024-10-03 17:57
Hey I want to contribute in this can you please assign it to me.

**Comment by mdazfar2** [comment] 2024-10-03 19:44
resolved

**Closed by mdazfar2** 2024-10-03 19:44 UTC
Labels: enhancement, gssoc-ext, need changes

**Comment by Abhi0049k** [comment] 2024-10-04 04:20
Hi @Kavita1928 and @mdazfar2 do I need to create a pr since the issue is already closed?

**Comment by Kavita1928** [comment] 2024-10-04 04:43
@Abhi0049k  NO, issue is resolved
