### ISSUE TITLE
[Feat] Remove Redundant About Us Page and Update Navbar Link

### ISSUE THREAD

**Issue by Pragyaa3** [mdazfar2/Ezyshop#1037] opened 2024-10-29 21:22 UTC
### Description

Currently, the site has an "About Us" section both on the home page and on a separate page accessed by the "About" button in the navbar.
To streamline navigation and reduce redundancy, the "About" button in the navbar could be updated to redirect users to the existing "Learn About Us" section on the home page. This way, the extra page can be removed, creating a cleaner user experience.

**Proposed Changes:**

1. Remove the duplicate "About Us" page.
2. Update the navbar's "About" button to link to the home page, focusing on the "About Us" section.

@md Please assign this issue to me and kindly mark this under Hacktoberfest and GSSoC-Extd24.

### Screenshots

![home](https://github.com/user-attachments/assets/c2ea486e-2024-4cdf-ad36-6b5ae8b46d07)
![about](https://github.com/user-attachments/assets/ff9a575b-59f4-4f12-bb94-322f053ec626)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-30 03:47
Hey @Pragyaa3, what exactly are you trying to say? I guess you’re talking about changing the navigation bar from about to about us, right? You just added the word Us, correct Pragya?

**Comment by Pragyaa3** [comment] 2024-10-30 06:42
@mdazfar2 Sorry Sir, I wasn't clear enough I guess. The "About" in navbar redirects to a page containing the content which is exactly same as the content in the "Home" page under "Learn About Us" section. 
So, I was thinking of removing the external "About" page and the About button in the navbar could be linked to the "Learn About Us " section in the home page.

**Comment by mdazfar2** [comment] 2024-10-30 07:38
@Pragyaa3, actually, this is what we want. This is not a bug; it is intended to be exactly like this. Please raise another issue, which I'm happy to assign to you. However, make sure that the issue you raise is valid and genuinely needs to be addressed on our website; otherwise, invalid issues will be closed. _Thank you!_

**Closed** 2024-10-30 07:38 UTC
Labels: enhancement, question, pending, isn't me
