### ISSUE TITLE
A clearer navigation bar would improve the user experience

### ISSUE THREAD

**Issue by shar2710** [mdazfar2/Ezyshop#1050] opened 2024-10-31 12:57 UTC
### Description

The navigation bar's current UI could be improved. For example, the logo is not clearly visible, which impacts brand visibility and overall aesthetics. This makes the navigation bar feel incomplete and harder to use at a glance.
please assign me with this @mdazfar2 

### Screenshots

![image](https://github.com/user-attachments/assets/dd374774-5cf9-4d74-8e9e-09457cc8862e)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-31 15:53
@shar2710, set your screen size to 100% and then check again. It looks good and nice. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank you!

**Closed by mdazfar2** 2024-10-31 15:54 UTC
Labels: bug
