### ISSUE TITLE
[BUG]  Website_appearance

### ISSUE THREAD

**Issue by piyahub** [mdazfar2/Ezyshop#959] opened 2024-10-25 08:45 UTC
### Description

The website does not appear good because of the right-side space left, which seams inconsistent. Moreover, the navigation bar also requires slight changes, to make all the items to come in a single line, it would look better. These are the changes I would like to present. Including a chat-bot would be a really helpful for the customers.

### Screenshots

![image](https://github.com/user-attachments/assets/4630101f-d5e2-485e-bf13-160d6188271e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-25 14:49
Hey @piyahub, the looks correct and very good on our side. Please check out the screenshot below for proof. I am closing the issue for now. Please raise another issue, which I am happy to assign to you, but make sure that the issue is valid and addresses something important on our website. Otherwise, invalid issues will be closed. Thank You!



![{E691A281-4DAD-46D8-B0CD-2BDE6FC96017}](https://github.com/user-attachments/assets/801202f9-2cd8-43dd-9a51-184c364b1b1d)

**Closed by mdazfar2** 2024-10-25 14:49 UTC
Labels: bug
