### ISSUE TITLE
[BUG] Navbar is not sticky

### ISSUE THREAD

**Issue by nishtha-902** [mdazfar2/Ezyshop#109] opened 2024-10-03 16:24 UTC
### Description

Navbar of this website is not sticky, @mdazfar2 please assign me this issue, I will fix this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-03 16:26
@nishtha-902 issue acknowledged! you are going to be assigned

**Comment by Ishajain0** [comment] 2024-10-03 19:17
please assign this take to me i already done this but the only issue is for mering a code .some issue is happend

**Comment by Ishajain0** [comment] 2024-10-03 19:18
please assign this task to me .

**Comment by Shantanu675** [comment] 2024-10-04 12:19
I believe I could solve this issue .Could you please assign it me ? Ii have a strong background of html and css .

**Comment by Ishajain0** [comment] 2024-10-04 12:40
The issue is already solved and merged to.

**Closed** 2024-10-04 13:52 UTC
Labels: bug, level1, gssoc-ext, assigned
